name: geo_integrity_score
description: "Detects spoofing risks and produces geo integrity scores from native sensor data."
version: 0.0.1
homepage: https://github.com/topmoveright/geo_integrity_score

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

topics:
  - location
  - security
  - monitoring
  - fraud-detection

screenshots:
  - description: Logo of Geo Integrity Score
    path: example/assets/geo_integrity_score.png

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.example.geo_integrity_score
        pluginClass: GeoIntegrityScorePlugin
      ios:
        pluginClass: GeoIntegrityScorePlugin


